"""empty message

Revision ID: 666de79eb54a
Revises: 44dc9c24e2fe
Create Date: 2023-10-22 22:50:00.715966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666de79eb54a'
down_revision = '44dc9c24e2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('environment_flags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_flags',
    sa.Column('flag_id', sa.TEXT(length=36), nullable=True),
    sa.Column('environment_id', sa.TEXT(length=36), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['flag_id'], ['flag.id'], )
    )
    # ### end Alembic commands ###
