"""empty message

Revision ID: 744bf68cadd5
Revises: 666de79eb54a
Create Date: 2023-10-24 11:03:02.249963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744bf68cadd5'
down_revision = '666de79eb54a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_flags',
    sa.Column('flag_id', sa.Text(length=36), nullable=False),
    sa.Column('environment_id', sa.Text(length=36), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['flag_id'], ['flag.id'], ),
    sa.PrimaryKeyConstraint('flag_id', 'environment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('environment_flags')
    # ### end Alembic commands ###
