"""empty message

Revision ID: c3526d903284
Revises: 8d378d121ff3
Create Date: 2023-10-30 21:09:54.771049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3526d903284'
down_revision = '8d378d121ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.Text(length=36)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment', schema=None) as batch_op:
        batch_op.drop_column('key')

    # ### end Alembic commands ###
